ept:
  git:
    contact:
      nom: ${ADMIN_NOM:Fall}
      prenom: ${ADMIN_PRENOM:Adama}
      email: ${ADMIN_EMAIL:adafall@ept.edu.sn}
spring:
  application:
    name: HelloSpringBoot
  datasource:
    username: ${DIC2_DB_USER}
    password: ${DIC2_DB_PWD}
    url: ${DIC2_DB_PWD}
  jpa:
    hibernate:
      ddl-auto: create
      #ddl-auto: none ne modifie pas le schema
      #ddl-auto: update mettre a jour les schema
      #ddl-auto: create supprime+creation
    show-sql: true
  profiles:
    active: tests, git